### ISSUE TITLE
When I add the cron module, node.js fails with error

### ISSUE THREAD

**Issue by Swizzler121** [peterthehan/discord-cron-bot#4]
SyntaxError: /home/[redacted]/src/widgets/discord-cron-bot/config.json: Unexpected token # in JSON at position 213

    at parse (<anonymous>)

    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22)

    at Module.load (internal/modules/cjs/loader.js:863:32)

    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

    at Module.require (internal/modules/cjs/loader.js:887:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at Object.<anonymous> (/home/[redacted]/src/widgets/discord-cron-bot/handlers/ready.js:1:29)

    at Module._compile (internal/modules/cjs/loader.js:999:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

    at Module.load (internal/modules/cjs/loader.js:863:32)

read and re-read the guide, looked through the other issues, did some googling... I got nothing.

the discord bot ran fine when the foobar module was in there, I deleted it and replaced it with the cron module, then this happened.

**Comment by Swizzler121** [comment]
Different error I just got when I re-ran it:

> spl-cron@1.0.0 start /[redacted]/discord/spl-cron
> node src/index.js

Error: Cannot find module 'cron'
Require stack:
- /[redacted]/src/widgets/discord-cron-bot/handlers/ready.js
- /[redacted]/src/core/getWidgetHandlerMap.js
- /[redacted]/src/core/loadWidgetListeners.js
- /[redacted]/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/[redacted]/discord/spl-cron/src/widgets/discord-cron-bot/handlers/ready.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/[redacted]/src/widgets/discord-cron-bot/handlers/ready.js',
    '/[redacted]/src/core/getWidgetHandlerMap.js',
    '/[redacted]/src/core/loadWidgetListeners.js',
    '/[redacted]/src/index.js'
  ]
}

**Comment by Swizzler121** [comment]
Resolved, Worked with them on the discord, was resolved by installing the cron dependancy (don't know how I missed that) and fixing some issues in my cron expression. Thank you!
